User.create!(
  [
    {
      nickname: "Hanako",
      email: "sample001@email.com",
      password: "password",
      image_url: "default_image",
      profile: "hello",
      family_name: "鈴木",
      first_name: "華子",
      ja_family_name: "スズキ",
      ja_first_name: "ハナコ",
      birthday: 19900611,
      authenticate_phone: "09000000000"
    },
    {
      nickname: "sasaki",
      email: "sample002@email.com",
      password: "password",
      image_url: "default_image",
      profile: "hello",
      family_name: "佐々木",
      first_name: "彩夏",
      ja_family_name: "ササキ",
      ja_first_name: "アヤカ",
      birthday: 19900611,
      authenticate_phone: "09000000001"
    },
    {
      nickname: "yuko",
      email: "sample003@email.com",
      password: "password",
      image_url: "default_image",
      profile: "hello",
      family_name: "新木",
      first_name: "優子",
      ja_family_name: "アラキ",
      ja_first_name: "ユウコ",
      birthday: 19900611,
      authenticate_phone: "09000000002"
    },
    {
      nickname: "jun",
      email: "sample004@email.com",
      password: "password",
      image_url: "default_image",
      profile: "hello",
      family_name: "岡田",
      first_name: "准一",
      ja_family_name: "オカダ",
      ja_first_name: "ジュンイチ",
      birthday: 19900611,
      authenticate_phone: "09000000003"
    },
    {
      nickname: "Alice",
      email: "sample005@email.com",
      password: "password",
      image_url: "default_image",
      profile: "hello",
      family_name: "有栖川",
      first_name: "有栖",
      ja_family_name: "アリスガワ",
      ja_first_name: "アリス",
      birthday: 19900611,
      authenticate_phone: "09000000005"
    },
    {
      nickname: "yui",
      email: "sample006@email.com",
      password: "password",
      image_url: "default_image",
      profile: "hello",
      family_name: "新垣",
      first_name: "結衣",
      ja_family_name: "アラガキ",
      ja_first_name: "ユイ",
      birthday: 19900611,
      authenticate_phone: "09000000006"
    },
    {
      nickname: "tetsu",
      email: "sample007@email.com",
      password: "password",
      image_url: "default_image",
      profile: "hello",
      family_name: "千葉",
      first_name: "哲也",
      ja_family_name: "チバ",
      ja_first_name: "テツヤ",
      birthday: 19900611,
      authenticate_phone: "09000000007"
    },
    {
      nickname: "Ayu",
      email: "sample008@email.com",
      password: "password",
      image_url: "default_image",
      profile: "hello",
      family_name: "高木",
      first_name: "歩",
      ja_family_name: "タカギ",
      ja_first_name: "アユム",
      birthday: 19900611,
      authenticate_phone: "09000000008"
    },
    {
      nickname: "shu",
      email: "sample009@email.com",
      password: "password",
      image_url: "default_image",
      profile: "hello",
      family_name: "海老",
      first_name: "寿司",
      ja_family_name: "エビ",
      ja_first_name: "スシ",
      birthday: 19900611,
      authenticate_phone: "09000000009"
    },
    {
      nickname: "KEN",
      email: "sample010@email.com",
      password: "password",
      image_url: "default_image",
      profile: "hello",
      family_name: "坂口",
      first_name: "健太郎",
      ja_family_name: "サカグチ",
      ja_first_name: "ケンタロウ",
      birthday: 19900611,
      authenticate_phone: "09000000010"
    }
  ]
)